Update requirements.txt
github actionのbuild中に `AttributeError: module 'jinja2' has no attribute 'contextfilter'` で転ける現象。
https://forums.docker.com/t/jinja-mkdocs-issue-breaks-docker101tutorial/122671
にあるsolutionを適用